apiVersion: cluster.x-k8s.io/v1alpha2
kind: Machine
metadata:
  name: capi-workload-controlplane-0
spec:
  version: v1.15.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: AWSMachine
metadata:
  name: capi-workload-controlplane-0
spec:
  instanceType: t3.small
