apiVersion: cluster.x-k8s.io/v1alpha2
kind: MachineDeployment
metadata:
  name: capi-workload-node
spec:
  replicas: 3
  template:
    spec:
      version: v1.15.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: AWSMachineTemplate
metadata:
  name: capi-workload-node
spec:
  template:
    spec:
      instanceType: t3.small
