apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: capi-workload01
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: AWSCluster
    name: capi-workload01
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: AWSCluster
metadata:
  name: capi-workload01
spec:
  region: ap-northeast-1
  sshKeyName: cluster-api-aws-default
